// react/src/components/Header.jsx
import useMenu from '../hooks/useMenu';
import Menu from "./Menu";
import { useResource } from '../glue';

const Header = ({ children }) => {
  const { resource } = useResource();
  const { items } = useMenu(resource);
  return (
    <header>
      {children}
      <Menu items={items} />
    </header>
  )
}

export default Header;

// vue/src/components/Header.vue
<script setup>
import { inject } from 'vue';
import Menu from './Menu.vue';
import useMenu from '../glue/composable/useMenu';
import { resourceKey } from "../glue/keys";

const resource = inject(resourceKey);
const { items } = useMenu(resource);

</script>
<template>
  <header>
    <slot></slot>
    <Menu :items="items" />
  </header>
</template>
