// react/src/App.jsx
import React from 'react'
import MatchResource from './pages/MatchResource';
import ArticlePage from './pages/ArticlePage';
import BasicPage from './pages/BasicPage';
import HomePage from './pages/HomePage';
import CollectionPage from './pages/CollectionPage';
import DefaultPage from './pages/DefaultPage';
import { useResource } from './glue';

function App() {
  const { resource, loading } = useResource();
  return (
    <React.StrictMode>
      <MatchResource resource={resource}>
        <HomePage type="home" />
        <BasicPage type="page" />
        <ArticlePage type="article" />
        <CollectionPage type="collection" />
        <DefaultPage default />
      </MatchResource>
      {loading && <p>Loading...</p>}
    </React.StrictMode>
  )
}

export default App

// vue/src/App.vue
<script setup>
import { inject, computed } from 'vue';
import { resourceKey, problemKey, loadingKey, followKey } from "./glue/keys";
import HomePage from './pages/HomePage.vue';
import ArticlePage from './pages/ArticlePage.vue';
import BasicPage from './pages/BasicPage.vue';
import CollectionPage from './pages/CollectionPage.vue';
import DefaultPage from './pages/DefaultPage.vue';
const pageMap = (type) => {
  const map = {
    'home': HomePage,
    'page': ArticlePage,
    'article': BasicPage,
    'collection': CollectionPage
  }
  return (type in map) ? map[type] : DefaultPage;
}
const resource = inject(resourceKey);
const problem = inject(problemKey);
const loading = inject(loadingKey);
const follow = inject(followKey);
const type = computed(() => pageMap(resource?.value?.type))
</script>

<template>
  <h1 v-if="loading">Loading...</h1>
  <component :is="type" />
</template>
