// vue/src/components/Link.vue
<script setup>
import { inject } from 'vue';
import { followKey } from "../glue/keys";
defineProps({
  link: Object,
})
const follow = inject(followKey);
</script>
<template>
  <a @click.prevent="follow(link.href)" :href="link.href" title="link.title" :class="[link.active ? 'is-active' : '']">
    {{ link.title }}
  </a>
</template>

// react/src/components/Link.jsx
import { useResource } from '../glue';

const Link = ({ link }) => {
  const { follow } = useResource();
  const { href, title, active } = link;
  const handleClick = (e) => {
    e.preventDefault();
    follow(link);
  }
  return <a onClick={handleClick} href={href} title={title} className={active ? 'is-active' : ''}>{title}</a>
}

export default Link;
